### ISSUE TITLE
Feature Request: Juni without docker

### ISSUE THREAD

**Issue by pdiazvargas** [eabglobal/juniper#9]
## What
Ability to package lambda functions without docker.

As a developer I am already using docker in my dev workflow. If I want to package a lambda function while I'm running inside a container, Juniper will need to spawn a container inside a container; which is far from ideal. I want to have the ability to package lambda functions in place.

As part of my CI/CD pipeline, my jobs are already running inside a docker container with the image of python that I desire. Having a dependency on docker and docker-compose forces a DevOps engineer to use the (docker in docker) dnd image.

## How
As part of the manifest file, there is already a `package` section where the developer can specify or override the output directory. Add a new flag to indicate whether to use docker or not.

```yaml

global:
  output: ./build
  docker: true

functions:
  sample:
    requirements: ./requirements.txt
    include:
      - ./
```

To prevent the current directory from being used for intermediate steps. Think about implementing this feature by using a tmp folder as the context where dependencies will be installed...

## Why
This feature fulfills a valid business need in which docker might not be a necessity. As it stands, juniper is too restrictive. Alleviating these restrictions to solve a business need is a priority.

**Comment by mcouthon** [comment]
Hey, just a thought - wouldn't you almost always want to use docker, for cases where your dev environment differs from the linux that runs inside lambda? If you have C binaries that you need to build, you'd rather have them built in the same env as the one in lambda, wouldn't you?

**Comment by pdiazvargas** [comment]
Hey @mcouthon, you're right. The more we use juniper internally, the more I see the benefits of using docker as the way to produce consistent builds independent of the environment. Like you mention, up to this point we have not had the need to run a build without using docker.
For now I'm going to close this feature request, until somebody brings this up as a valid need. Also, trying to keep the feature offerings of juniper with docker and without docker at the same time, would significantly add complexity to the codebase.
Thanks for the feedback!

**Comment by mcouthon** [comment]
Thank you for the answer, and the amazing package!
